### ISSUE TITLE
Create GitHub set-up guide

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/CEPO-SMS#4]

**Comment by PeaceGeeksProjects** [comment]
Completed.  Please review & Close.
https://docs.google.com/document/d/1Pt6qV8Nw25JRCBWD71WyNhHy8Ibwj4cZaRWtZafkjQ8/edit

**Comment by PeaceGeeks** [comment]
Please send to James and ask him to create a GitHub account in advance of our meeting on Monday.

**Comment by PeaceGeeksProjects** [comment]
email sent...
